# .kuma/base.yaml

# variables:
# packageName = github.com/arthurbcp/kuma-hello-world
# serviceName = customPrint
# msg = Hello, Kuma!

#  Global variables to be used in all the templates.
global:
  packageName: "{{.data.packageName}}"

# Structure of folders and files that will be generated
structure:
  # main.go
  main.go:
    # o template que será usado com base para a criação do arquivo main.go
    template: templates/Main.go

    # variáveis que serão utilizadas dentro do template
    data:
      # name: CustomPrint
      service: { { toPascalCase .data.serviceName } }

      # msg: Hello, Kuma!
      msg: { { .data.msg } }
