name: Create Beta Release on Merge to Develop

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  create-beta-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine Next Beta Tag
        id: get_beta_tag
        run: |
          # Fetch all tags
          git fetch --tags

          # Get the latest tag matching the beta pattern
          latest_beta_tag=$(git tag --list '*-beta*' | sort -V | tail -n1)

          echo "Latest beta tag: $latest_beta_tag"

          if [ -z "$latest_beta_tag" ]; then
            # If no beta tags exist, derive from the latest non-beta tag
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest non-beta tag: $latest_tag"

            if [ -z "$latest_tag" ]; then
              # If no tags exist at all, start from v1.0.0-beta.1
              next_beta_tag="v1.0.0-beta.1"
            else
              # Extract version numbers from the latest tag
              major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
              minor=$(echo $latest_tag | cut -d. -f2)
              patch=$(echo $latest_tag | cut -d. -f3)

              # Start beta versions at patch level
              next_beta_tag="v$major.$minor.$patch-beta.1"
            fi
          else
            # Extract the current beta version number
            base_tag=$(echo $latest_beta_tag | sed -E 's/(v[0-9]+\.[0-9]+\.[0-9]+-beta\.)[0-9]+/\1/')
            beta_num=$(echo $latest_beta_tag | grep -o -E '[0-9]+$')

            # Increment the beta version number
            next_beta_num=$((beta_num + 1))
            next_beta_tag="${base_tag}${next_beta_num}"
          fi

          echo "Next beta tag: $next_beta_tag"
          echo "::set-output name=TAG::$next_beta_tag"

      - name: Create Tag
        run: |
          git tag ${{ steps.get_beta_tag.outputs.TAG }}
          git push origin ${{ steps.get_beta_tag.outputs.TAG }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_beta_tag.outputs.TAG }}
          release_name: Release ${{ steps.get_beta_tag.outputs.TAG }}
          body: "Automatically generated **beta** release for `${{ steps.get_beta_tag.outputs.TAG }}`."
          draft: false
          prerelease: true
